define([
    'utils',
    'loop',
    'gifHandler',
    'camera',
    'objectpool',
    'spriteobject',
    'packer',
    'spritesheet',
    'spriterenderer',
    'collection',
    'mouse',
    'loader',
    'engine',
], function(
    Utils,
    Loop,
    GifHandler,
    Camera,
    ObjectPool,
    SpriteObject,
    Packer,
    SpriteSheet,
    SpriteRenderer,
    Collection,
    Mouse,
    Loader,
    Engine,
) {

    return {
        Utils,
        Loop,
        GifHandler,
        Camera,
        ObjectPool,
        SpriteObject,
        SpriteSheet,
        SpriteRenderer,
        Collection,
        Mouse,
        Loader,
        Engine,
    };
});
